#!/usr/bin/env node
/**
 * TabFlow project cleanup.
 *
 * Run with `npm run clean`. Cross-platform (Node only — no shell required).
 *
 * Removes:
 *   - dist/ folders under packages/ (regenerated by `npm run build`)
 *   - All `zi*` sandbox temp files in the project root (left behind by
 *     restricted-filesystem sandbox runs of zip — harmless on Windows
 *     but clutters the project folder)
 *   - .release-tmp-chrome-store/ staging directory (the package script
 *     usually cleans this up itself, but a leftover from a sandbox run
 *     can survive)
 *   - vite.config.ts.timestamp-*.mjs (Vite build temp files)
 *   - manifest.json.tmp anywhere under packages/ (5-byte stray from
 *     debugging — never present in a normal repo)
 *   - tabflow-*.zip release zips for any version OTHER than the version
 *     currently in manifest.chrome.json. The current version's zips are
 *     preserved so the most recent release is always there to upload.
 *   - Legacy unversioned zips: tabflow-firefox.zip, tabflow-source.zip
 *     (replaced by the versioned filenames)
 *
 * Prints a summary of what was removed.
 */

import { readdirSync, readFileSync, rmSync, statSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

let removedCount = 0;
let removedBytes = 0;

const tryRemove = (absPath, label) => {
  try {
    const stats = statSync(absPath);
    const bytes = stats.isDirectory() ? sizeOfDir(absPath) : stats.size;
    rmSync(absPath, { recursive: true, force: true });
    removedCount++;
    removedBytes += bytes;
    const sizeStr = formatBytes(bytes);
    console.log(`  ✓ ${label}: ${path.relative(root, absPath)} (${sizeStr})`);
  } catch (err) {
    if (err.code !== 'ENOENT') {
      console.warn(`  ! could not remove ${path.relative(root, absPath)}: ${err.code || err.message}`);
    }
  }
};

const sizeOfDir = (dir) => {
  let total = 0;
  try {
    for (const name of readdirSync(dir)) {
      const p = path.join(dir, name);
      try {
        const s = statSync(p);
        if (s.isDirectory()) total += sizeOfDir(p);
        else total += s.size;
      } catch { /* skip */ }
    }
  } catch { /* skip */ }
  return total;
};

const formatBytes = (bytes) => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
};

// Read current version from the Chrome manifest (the source of truth for
// release versioning).
const manifestPath = path.join(root, 'packages/browser-extension/public/manifest.chrome.json');
let currentVersion = '';
try {
  currentVersion = JSON.parse(readFileSync(manifestPath, 'utf8')).version || '';
} catch {
  console.warn(`[clean] could not read manifest version; will skip the "keep current release" check`);
}

console.log(`\n[clean] Cleaning up project (current version: ${currentVersion || 'unknown'})\n`);

// ─── 1. dist/ folders ────────────────────────────────────────────────
{
  const packagesDir = path.join(root, 'packages');
  if (existsSync(packagesDir)) {
    for (const pkg of readdirSync(packagesDir)) {
      const distPath = path.join(packagesDir, pkg, 'dist');
      if (existsSync(distPath)) tryRemove(distPath, 'build output');
    }
  }
}

// ─── 2. zi* sandbox temp files in project root ───────────────────────
{
  for (const name of readdirSync(root)) {
    if (/^zi[A-Za-z0-9]+$/.test(name)) {
      const p = path.join(root, name);
      try {
        if (statSync(p).isFile()) tryRemove(p, 'sandbox temp');
      } catch { /* skip */ }
    }
  }
}

// ─── 3. .release-tmp-* directories ────────────────────────────────────
{
  for (const name of readdirSync(root)) {
    if (name.startsWith('.release-tmp-')) {
      const p = path.join(root, name);
      try {
        if (statSync(p).isDirectory()) tryRemove(p, 'release staging');
      } catch { /* skip */ }
    }
  }
}

// ─── 4. Vite timestamp temp files (anywhere under packages/) ─────────
{
  const walk = (dir) => {
    let entries;
    try { entries = readdirSync(dir); } catch { return; }
    for (const name of entries) {
      const p = path.join(dir, name);
      let s;
      try { s = statSync(p); } catch { continue; }
      if (s.isDirectory()) {
        if (name === 'node_modules' || name === '.git' || name === 'dist') continue;
        walk(p);
      } else if (name.startsWith('vite.config.ts.timestamp-')) {
        tryRemove(p, 'vite temp');
      } else if (name === 'manifest.json.tmp') {
        tryRemove(p, 'stray tmp');
      }
    }
  };
  walk(path.join(root, 'packages'));
}

// ─── 5. Old release zips ─────────────────────────────────────────────
{
  const versionedRe = /^tabflow-(?:chrome|firefox|source)-(\d+\.\d+\.\d+)(?:-store)?\.zip$/;
  for (const name of readdirSync(root)) {
    // Legacy unversioned: always remove
    if (name === 'tabflow-firefox.zip' || name === 'tabflow-source.zip' || name === 'tabflow-chrome.zip') {
      tryRemove(path.join(root, name), 'old release (unversioned)');
      continue;
    }
    const m = name.match(versionedRe);
    if (m) {
      const fileVersion = m[1];
      if (fileVersion !== currentVersion) {
        tryRemove(path.join(root, name), `old release v${fileVersion}`);
      }
    }
  }
}

console.log(`\n[clean] Done. Removed ${removedCount} item(s), freed ${formatBytes(removedBytes)}.`);
if (currentVersion) {
  console.log(`[clean] Kept current-version release zips for v${currentVersion}.`);
}
console.log();
